#include <TNtuple.h>

void MakeHists(){

  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.

  TFile *f = new TFile("B4.root");
  TTree *tt = (TTree*)f->Get("B4");



  Double_t Eabs,Egap, Labs,Lgap;


  tt->SetBranchAddress("Eabs",&Eabs);
  tt->SetBranchAddress("Egap",&Egap);
  tt->SetBranchAddress("Labs",&Labs);
  tt->SetBranchAddress("Lgap",&Lgap);


  // create a histograms
  TH1F *hEabs   = new TH1F("hEabs","Eabs distribution",100,0.,1000.);


  //read all entries and fill the histograms
  Int_t nentries = (Int_t)tt->GetEntries();
  std::cout<<" nentries is "<<nentries<<std::endl;
  for (Int_t i=0; i<nentries; i++) {
    tt->GetEntry(i);
    cout<<"event number is "<<i<<" Eabs Egap Labs Lgap "<<Eabs<<" "<<Egap<<" "<<Labs<<" "<<Lgap<<endl;
    hEabs->Fill(Eabs);
  }
  // We do not close the file. We want to keep the generated
  // histograms we open a browser and the TreeViewer
  if (gROOT->IsBatch()) return;
  TCanvas *c1 = new TCanvas("c1","Vertex Plots",200,10,700,500);
  hEabs->Draw();
  c1->Modified();
  c1->Update();
  c1->Print("c1.pdf",".pdf");

  //  t1->StartViewer();

  tt->ResetBranchAddresses();



  //In the browser, click on "ROOT Files", then on "tree1.root"
  //You can click on the histogram icons in the right panel to draw
  //them in the TreeViewer, follow the instructions in the Help.
}
